Dictionary = {
      Ind: "Independent",
      MMA: "Muttahida Majlis-e-Amal",
      "PPP-S": "Pakistan People's Party (Sherpao)",
      "PML-Q": "Pakistan Muslim League (Q)",
      "PML-C": "Pakistan Muslim League (Council)",
      CML: "Conventional Muslim League",
      PPP: "Pakistan People's Party",
      "PML-N": "Pakistan Muslim League (Nawaz)",
      NA: "National Alliance",
      PTI: "Pakistan Tehrik-e-Insaf",
      "PML-J": "Pakistan Muslim League (Junejo)",
      PAT: "Pakistan Awami Tehreek",
      SPP: "Shia Political Party",
      "PML-Z": "Pakistan Muslim League (Zia)",
      "PML-F": "Pakistan Muslim League (Functional)",
      MQM: "Muttahida Qaumi Movement",
      "MQM-H": "Muttahida Qaumi Movement (Haqiqi)",
      PKMAP: "Pakhtunkhwa Milli Awami Party",
      JWP: "Jamhoori Watan Party",
      BNP: "Balochistan National Party",
      "BNP-A": "Balochistan National Party (Awami)",
      ANP: "Awami National Party",
      TI: "Tehrik-e-Istiqlal",
      PDP: "Pakistan Democratic Party",
      BNM: "Balochistan National Movement",
      "BNM-M": "Balochistan National Movement (Mengal)",
      "BNM-H": "Balochistan National Movement (Hayee)",
      "PPP-SB": "Pakistan People's Party (Shaheed Bhutto)",
      NPP: "National People's Party",
      "NPP-K": "National People's Party (Khar)",
      JUI: "Jamiat Ulema-e-Islam",
      "JUI-NI": "Jamiat Ulema-e-Islam + Nizam e Islam",
      "JUI-F": "Jamiat Ulema-e-Islam (Fazl)",
      "JUI-S": "Jamiat Ulema-e-Islam (Sami)",
      "JUI-N": "Jamiat Ulema-e-Islam (Noorani)",
      MIP: "Milli Ittehad Pakistan",
      IJM: "Islamic Jamhoori Mahaz",
      MDM: "Muttahida Deeni Mahaz",
      PKQP: "Pakhtunkhwa Qaumi Party",
      PIF: "Pakistan Islamic Front",
      NDA: "National Democratic Alliance",
      IJI: "Islami Jamhoori Ittehad",
      "JUI-D": "Jamiat Ulema-e-Islam (Darkhasti)",
      PAI: "Pakistan Awami Ittehad",
      BNA: "Balochistan National Alliance",
      "PML-MQ": "Pakistan Muslim League (MQ)",
      PNP: "Pakistan National Party",
      PMAI: "Pakistan Milli Awami Ittehad",
      PDA: "People's Democratic Alliance",
      "JUP-N": "Jamiat Ulema-e-Pakistan (Noorani)",
      SNF: "Sindh National Front",
      SNA: "Sindh National Alliance",
      "AT-PG": "Awami Tehreek (Paleejo Group)",
      PNA: "Pakistan National Alliance",
      PPNAP: "Pakistan Pakhtunkhwa National Awami Party",
      NP: "National Party",
      SUP: "Sindh United Party",
      AML: "Awami Muslim League",
      PCM: "Pakistan Citizen's Movement",
      "QWP-S": "Qaumi Watan Party (Sherpao)",
      AJI: "Awami Jamhoori Ittehad",
      APML: "All Pakistan Muslim League",
      JI: "Jamat e Islami",
      BNAP: "Bahawalpur National Awami Party",
      STP: "Sindh Taraqi Passand Party",
      BAP: "Balochistan Awami Party",
      GDA: "Grand Democratic Alliance",
      TLP: "Tehreek-e-Labbaik Pakistan",
      PAR: "Pakistan Awami Raj",
      PRP: "Pakistan Rah-e-haq Party",
      "NAP-W": "National Awami Party (Wali)",
      "NAP-B": "National Awami Party (Bhashani)",
      MJUP: "Markazi Jamiat Ulema-e-Pakistan",
      AL: "Awami League",
      PNL: "Pakistan National League",
      MJAH: "Markazi Jamiat-e-Ahle-Hadees",
      JGMD: "Jatiya Gana Mukti Dal",
      IGD: "Islami Gonotontri Dal",
      IPP: "Istehkam-e-Pakistan Party",
      "PTI-IND": "Independent (PTI Backed)",
  };

  '{"Pakistan Muslim League (N)":"PML-N","Independent":"IND","Pakistan Muslim League":"PML-Q","Istehkam-e-Pakistan Party":"IPP","Pakistan Peoples Party Parliamentarians":"PPP","Pakistan Muslim League (Zia-Ul-Haq)":"PML-Z","Muttahida Qaumi Movement Pakistan":MQM}'